[package]
name = "nikka-leaps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
clap = { version = "3.2.22", features = ["derive", "cargo"] }
ctrlc = "3.2.2"
libloading = "0.7.3"
nvml-wrapper = "0.8.0"
nvml-wrapper-sys = "0.6.0"
once_cell = "1.15.0"
